### PR TITLE
fixes #42 (Added a favicon as initially there was no favicon)

### LINKED ISSUE #42: No favicon in main page
## Description
As a USER,
I need to see a favicon in the title bar along with title i.e GHC 2018.
The favicon is included in all websites and it makes the title bar complete along with the title.

## Mocks
At present there is no favicon in the title bar of the website.

slackghcnofavioc

## Acceptance Criteria
There should be a favicon in the title bar. 

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
.5 hours

### PR DESCRIPTION
**Pull request by sarnava1**
This PR adds a favicon to slack-ghc as initially there was no favicon

faviconinghc

Fixes #42

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sarnava1** [comment]
@Tharangi @sammy1997 @bethanyr @ExactlyMay @isabelcosta @kanmodi please review my PR.

**Comment by sammy1997** [comment]
@anumehaagrawal @BaaniLeen WDYT? LGTM! Please have a look

**Comment by sarnava1** [comment]
@sammy1997 thanks a lot for your review. I use atom. I will surely learn from your guidance. Thank you.

**Comment by anumehaagrawal** [comment]
@sarnava1  Looks good to me !

**Comment by anumehaagrawal** [comment]
@Tharangi @bethanyr  I have approved the PR , could you please have a look and merge it :)

**Comment by sarnava1** [comment]
Thanks @anumehaagrawal.

**Comment by bethanyr** [comment]
@sarnava1 - if you are unable to update the server.js file - let me know and i can try and fix it and merge it on my end this weekend.

**Comment by sarnava1** [comment]
@bethanyr actually i am not at my place and am not having proper internet connectivity. I still tried to resolve the conflict using my phone and this it resulted in some silly mistakes and thus all this codacy errors. I will reach home this Monday and will resolve all the errors. I am very sorry for being outside and I hope it does not create a problem.

**Comment by f2015537** [comment]
@bethanyr  I think the documentation needs to be updated so that contributors don't get these intimidating Codacy errors while making a PR. Can I work on that?

**Pull request closed without merging**
